// English translations for the existing Japanese / Chinese interface.
export const EN = {
  "不到 1 分钟": "Less than 1 minute",
  "分钟": "minutes",
  "小时": "hours",
  "无法保存，关闭页面后数据将丢失。": "Unable to save. Your data will be lost when you close this page.",
  "你正在借用一把伞，请先归还。": "You already have an umbrella on loan. Please return it first.",
  "目前没有借用中的伞。": "You do not have an umbrella on loan.",
  "该伞点暂无可借雨伞。": "No umbrellas are available at this station.",
  "该伞点已满，请选择其他归还点。": "This station is full. Please choose another return station.",
  "最多收藏两个伞点，请先取消一个收藏。": "You can save up to two favorite stations. Remove one to add another.",
  "请选择 1–5 星评分。": "Please choose a rating from 1 to 5 stars.",
  "请重新完成伞点认证。": "Please verify the station again.",
  "操作未完成，请重试。": "The action could not be completed. Please try again.",
  "演示数据": "Demo data",
  "访客": "Guest",
  "声音认证（演示）": "Sound verification (demo)",
  "代码输入": "Station code",
  "二维码（演示）": "QR code (demo)",
  "摄像头扫码": "Camera scan",
  "旧版认证": "Legacy verification",
  "借用期限：一周": "Loan period: one week",
  "正常使用免费；逾期未还或损坏，赔偿金额为 ¥2,000。": "Normal use is free. An overdue or damaged umbrella incurs ¥2,000 compensation.",
  "使用规则": "Loan rules",
  "借用期限为一周": "Borrow for up to one week",
  "借用超过一周未归还，或雨伞损坏，赔偿金额为 2,000 日元。两项同时发生时每把伞计一次。": "Compensation is ¥2,000 if the umbrella is not returned within one week or is damaged. If both apply, it is charged once per umbrella.",
  "归还期限 · 借用一周": "Return deadline · One-week loan",
  "演示时钟": "Demo clock",
  "借用期限进度": "Loan period progress",
  "赔偿金额（演示）": "Compensation (demo)",
  "逾期未还": "Overdue",
  "已申报损坏": "Damage reported",
  "未结算 · 无真实扣款": "Unpaid demo amount · No real charge",
  "期限内完好归还，使用费用为零。": "Return it on time and undamaged for free use.",
  "这是旧版开始的演示借用，赔偿规则从下次借用起适用。": "This loan began under the previous demo rules. Compensation applies from your next loan.",
  "借伞成功。": "Your umbrella is ready.",
  "请取走雨伞，借用期限为一周。": "Take your umbrella and return it within one week.",
  "借用伞点": "Pickup station",
  "雨伞编号": "Umbrella ID",
  "认证方式": "Verification method",
  "查看借用状态": "View my loan",
  "基础使用费": "Base usage fee",
  "损坏": "Damaged",
  "：每把伞 2,000 日元，不产生真实账单或扣款。": ": ¥2,000 per umbrella. No real invoice or charge is created.",
  "期限内完好归还，正常使用免费。": "Normal use is free when returned on time and undamaged.",
  "旧版借用不追加赔偿金额。": "No compensation is added to legacy loans.",
  "申报雨伞损坏": "Report umbrella damage",
  "损坏的雨伞会记录为待检修，避免再次借出。": "Damaged umbrellas are marked for inspection and cannot be borrowed again.",
  "损坏情况（选填）": "Damage details (optional)",
  "例如：伞骨折断": "For example: a broken rib",
  "记录损坏（演示）": "Save damage report (demo)",
  "撤销损坏申报": "Withdraw damage report",
  "仅保存在当前浏览器，此操作不会完成归还。": "Saved only in this browser. Reporting damage does not complete the return.",
  "首页": "Home",
  "附近伞点": "Nearby stations",
  "我的借用": "My umbrella",
  "优惠与服务": "Offers & services",
  "个人中心": "My account",
  "陪伴每个雨天": "Here for every rainy day",
  "主菜单": "Main menu",
  "从一把伞开始，<br>让城市多一点温暖。": "One shared umbrella.<br>A kinder city.",
  "广告主后台": "For advertisers",
  "使用指南": "How it works",
  "共享一把伞，连接一座城。": "Share an umbrella. Connect a community.",
  "使用帮助": "Help",
  "体验版：天气、伞点、库存及广告均为示例，不会产生真实借还操作。": "Prototype: weather, stations, stock and advertisements are examples. No real umbrella transactions take place.",
  "手机导航": "Mobile navigation",
  "借用中": "On loan",
  "伞点": "Stations",
  "取消收藏": "Remove favorite",
  "收藏": "Add favorite",
  "详情": "Details",
  "国士馆大学": "Kokushikan University",
  "梅丘": "Umegaoka",
  "羽根木公园": "Hanegi Park",
  "当前位置（示例）": "Your location (example)",
  "伞点示意图 · 非真实地图": "Station diagram · Not a real map",
  "查看伞点": "View stations",
  "归还到这里": "Return here",
  "查看详情": "View details",
  "下雨天，也能<span>轻松出发。</span>": "Rainy day?<span>Keep moving.</span>",
  "需要时借一把，顺路就能归还。": "Borrow when you need one. Return it along your way.",
  "世田谷 · 国士馆大学周边": "Setagaya · Near Kokushikan University",
  "你有一把正在使用的伞": "You have an umbrella on loan",
  "归还期限": "Return deadline",
  "查看借用": "View my umbrella",
  "世田谷区": "Setagaya",
  "别让天气，打乱你的计划。": "Keep your plans, whatever the weather.",
  "小雨转多云": "Light rain, then cloudy",
  "降水概率": "Chance of rain",
  "回家的路上，也有一把伞等你。": "An umbrella is waiting on your way home.",
  "让心情，也放个晴。": "A little sunshine for your day.",
  "这一场雨，<br>让我们共享一把伞。": "One rainy day.<br>One shared umbrella.",
  "借用费用": "Loan fee",
  "一周内使用": "Up to one week",
  "寻找归还点": "Find a return station",
  "借一把伞": "Borrow an umbrella",
  "由社区赞助商提供支持": "Supported by local sponsors",
  "附近的伞点": "Stations nearby",
  "一把好借、好还的伞，就在你身边。": "Easy to borrow. Easy to return. Right around you.",
  "查看全部": "View all",
  "距离及步行时间为示例参考值": "Distances and walking times are examples",
  "借一把，走一程，传一份温暖。": "Borrow an umbrella. Share a little kindness.",
  "找到附近伞点": "Find a station",
  "一周内归还": "Return within one week",
  "寻找归还伞点": "Find a return station",
  "可归还到任意有空位的伞点，无需原路返回。": "Return to any station with space. No need to go back to the pickup station.",
  "在你的城市，找到顺路的那把伞。": "Find an umbrella along your way.",
  "获取当前位置": "Use my location",
  "搜索车站或伞点名称": "Search station names or locations",
  "搜索伞点": "Search stations",
  "列表": "List",
  "地图": "Map",
  "全部": "All",
  "可以归还": "Returns available",
  "可以借用": "Umbrellas available",
  "我的收藏": "Favorites",
  "按 GPS 位置估算（步行时间为示例）": "Estimated from GPS location; walking times are examples",
  "世田谷周边 · 按示例距离排序": "Around Setagaya · Sorted by example distance",
  "伞点、库存及坐标为演示数据。GPS 仅用于估算距离，不会保存。营业时间为示例，未关联借还限制。": "Stations, stock and coordinates are demo data. GPS is used only to estimate distance and is not saved. Example opening hours do not restrict demo loans or returns.",
  "没有找到伞点": "No stations found",
  "请更换关键词或筛选条件。": "Try another search or filter.",
  "重置搜索": "Reset search",
  "社区咖啡店 · 示例广告": "Neighborhood café · Sample ad",
  "雨天，喝杯咖啡再出发。": "Wait out the rain with a coffee.",
  "饮品立减 50 日元": "¥50 off a drink",
  "街角小店 · 示例广告": "Local shop · Sample ad",
  "在熟悉的街角，发现小惊喜。": "Find a little surprise around the corner.",
  "购物享九折": "10% off your shopping",
  "返回伞点列表": "Back to stations",
  "从这里出发，继续今天的旅程。": "Pick up an umbrella and carry on with your day.",
  "切换收藏": "Toggle favorite",
  "可借雨伞": "Umbrellas available",
  "把": "umbrellas",
  "距离（示例）": "Distance (example)",
  "营业时间（示例）": "Opening hours (example)",
  "24 小时": "24 hours",
  "轻松借用，<br>顺路归还。": "Borrow with ease.<br>Return along your way.",
  "免费": "Free",
  "可在任意有空位的伞点归还": "Return to any station with space",
  "借用期限为一周（7 天）": "One-week loan period (7 days)",
  "查看正在借用的伞": "View my current umbrella",
  "社区支持，让每一把伞免费共享": "Community support keeps umbrella sharing free",
  "广告赞助商的支持，让雨天的出行更轻松。": "Our sponsors help make rainy-day journeys easier.",
  "雨天，也有值得停留的地方": "Places worth stopping for on a rainy day",
  "赞助商 · 示例": "Sponsor · Example",
  "雨天出行，多一份轻松。": "An easier way to travel in the rain.",
  "目前没有借用中的雨伞": "No umbrella on loan",
  "去附近的伞点，找一把等你出发的伞吧。": "Find an umbrella waiting for you at a nearby station.",
  "寻找伞点": "Find a station",
  "和这把伞，再走一程。": "A little further, together.",
  "借用期限为一周，记得按时归还。": "Your loan lasts one week. Please return your umbrella on time.",
  "已逾期": "Overdue",
  "使用中": "In use",
  "基础使用费 ¥0": "Base usage fee ¥0",
  "已使用": "Time used",
  "借用开始": "Loan started",
  "附近可归还伞点": "Nearby return stations",
  "选择归还伞点": "Choose a return station",
  "已记录损坏申报": "Damage report saved",
  "如果雨伞损坏了": "Is your umbrella damaged?",
  "归还后将列为待检修，不会再次借出。": "After return, it will be kept for inspection and cannot be borrowed.",
  "请在归还前记录损坏情况。": "Please report any damage before returning it.",
  "编辑": "Edit",
  "申报": "Report",
  "把这份温暖，留给下一位。": "Leave a little kindness for the next person.",
  "归还前，请轻轻甩去水滴，将雨伞收好。": "Shake off the rain and fold your umbrella before returning it.",
  "仅切换本次借用的演示时钟，查看逾期状态，不修改设备时间。": "Change only this loan's demo clock to preview an overdue return. Your device clock is unchanged.",
  "恢复当前时间": "Use current time",
  "模拟逾期 1 小时": "Simulate 1 hour overdue",
  "下一个雨天，我们再见。": "See you on the next rainy day.",
  "归还成功，感谢你参与共享。": "Return complete. Thank you for sharing.",
  "本次借用": "This loan",
  "使用时长": "Duration",
  "未结算 · 不会产生真实账单": "Unpaid demo amount · No real invoice",
  "损坏雨伞已列为待检修，不会计入可借库存。": "This damaged umbrella is awaiting inspection and is not included in available stock.",
  "此记录使用了逾期情景的演示时钟。": "This record used the overdue scenario's demo clock.",
  "旧版借用": "Legacy loan",
  "借出": "Borrowed",
  "归还": "Returned",
  "这次体验怎么样？": "How was your experience?",
  "你的反馈，让每个雨天更美好。": "Your feedback makes rainy days better.",
  "五星评价": "Five-star rating",
  "星": "stars",
  "写下感受或改进建议（选填）": "Share your thoughts or suggestions (optional)",
  "反馈": "Feedback",
  "更新评价": "Update rating",
  "保存评价": "Save rating",
  "体验版评价仅保存在当前浏览器。": "Demo feedback is stored only in this browser.",
  "返回首页": "Back to home",
  "每一次借用，都留在这里。": "Every shared journey, saved here.",
  "编辑资料": "Edit profile",
  "无需登录即可体验": "Explore without signing in",
  "本地演示资料": "Local demo profile",
  "退出演示账号": "Sign out of demo account",
  "登录 / 注册": "Sign in / Register",
  "借用次数": "Total loans",
  "次": "loans",
  "累计基础使用费": "Total base usage fees",
  "收藏伞点": "Favorite stations",
  "把常用伞点，收藏在这里。": "Keep your regular stations close.",
  "点击爱心，最多收藏两个伞点。": "Tap the heart to save up to two stations.",
  "借用记录": "Loan history",
  "赔偿 · 演示": "Compensation · Demo",
  "从借用第一把伞开始": "Start with your first umbrella",
  "归还后，借用记录会显示在这里。": "Completed loans will appear here after you return an umbrella.",
  "使用指南与常见问题": "How it works & FAQs",
  "重置演示数据": "Reset demo data",
  "给雨天，加一点小惊喜。": "A little extra for your rainy day.",
  "来自支持共享雨伞的社区赞助商。": "Offers from local sponsors who support umbrella sharing.",
  "优惠券仅供体验，无法在真实门店使用。": "These demo coupons cannot be redeemed at real stores.",
  "已领取的优惠券": "Saved coupons",
  "仅限演示 · 无法在门店使用": "Demo only · Not valid in stores",
  "已使用（演示）": "Used (demo)",
  "模拟使用": "Try using coupon",
  "领取一份雨天的小惊喜": "Save a rainy-day treat",
  "点击上方赞助商卡片，即可领取优惠券。": "Select a sponsor card above to save a coupon.",
  "广告支持，让共享雨伞保持免费。": "Advertising helps keep umbrella sharing free.",
  "让社区的支持，成为日常的小优惠。积分、步数联动及支付功能仍处于构想阶段。": "Community support brings everyday offers. Points, step tracking and payments are still concepts.",
  "大学周边": "Around universities",
  "车站周边": "Around stations",
  "商业设施": "Shopping areas",
  "让行走在城市中的雨伞，传递你的品牌。": "Let umbrellas carry your brand through the city.",
  "申请广告投放": "Apply to advertise",
  "此为演示后台。统计与活动均为示例，申请仅保存在当前浏览器。": "This is a demo dashboard. Metrics and campaigns are examples. Applications are saved only in this browser.",
  "预计广告浏览量": "Estimated ad views",
  "人": "people",
  "较上月（示例）": "Compared with last month (example)",
  "广告伞借用次数": "Sponsored umbrella loans",
  "广告伞投放伞点": "Stations with sponsored umbrellas",
  "处": "stations",
  "正在投放的广告": "Active campaigns",
  "街角咖啡｜雨天优惠": "Corner Café | Rainy-day offer",
  "投放时间": "Campaign dates",
  "投放区域": "Campaign area",
  "投放中": "Active",
  "世田谷小店｜社区购物": "Setagaya Shop | Community shopping",
  "在三个区域连接社区": "Connect the community across three areas",
  "伞点数量为示例": "Station counts are examples",
  "广告申请草稿": "Advertising application drafts",
  "本地草稿": "Local draft",
  "点击申请广告投放，填写并保存你的方案。": "Select Apply to advertise to create and save your proposal.",
  "Rain Flow As 共享借伞": "Rain Flow As · Shared umbrellas",
  "关闭": "Close",
  "你好，新朋友。": "Hello, new friend.",
  "欢迎回来。": "Welcome back.",
  "登录": "Sign in",
  "注册": "Register",
  "此为演示表单，请勿输入真实密码。": "This is a demo form. Do not enter a real password.",
  "昵称": "Display name",
  "雨天旅人": "Rainy-day traveler",
  "邮箱（演示）": "Email (demo)",
  "密码（演示）": "Password (demo)",
  "创建演示资料": "Create demo profile",
  "登录演示账号": "Sign in to demo account",
  "不会进行真实认证，也不会保存密码。": "No real authentication takes place. Passwords are never saved.",
  "LINE 登录规划中": "LINE sign-in is planned",
  "编辑个人资料": "Edit profile",
  "演示资料仅保存在当前浏览器。": "Your demo profile is saved only in this browser.",
  "姓名假名（选填）": "Name in kana (optional)",
  "年龄（选填）": "Age (optional)",
  "所在区域（选填）": "Area (optional)",
  "兴趣爱好": "Interests",
  "音乐": "Music",
  "阅读": "Reading",
  "自驾": "Driving",
  "散步": "Walking",
  "保存资料": "Save profile",
  "下雨了，停下来喝一杯吧。": "Pause for a coffee while it rains.",
  "来自街角小店的小惊喜。": "A little surprise from your local shop.",
  "任意一杯饮品可用的演示优惠券。": "A demo coupon for one drink.",
  "用于体验购物流程的演示优惠券。": "A demo coupon for trying the shopping flow.",
  "演示专用优惠券": "Demo coupon",
  "无法在真实门店抵扣或兑换，可以体验领取及模拟使用流程。": "Not valid for payment or redemption in real stores. Try saving and using it in this demo.",
  "已领取 · 查看优惠券": "Saved · View coupons",
  "领取优惠券": "Save coupon",
  "演示申请将保存为本地草稿，不会发送给任何人。": "Your demo application will be saved locally. It will not be sent to anyone.",
  "企业 / 门店名称": "Company / Store name",
  "例如：世田谷咖啡": "For example: Setagaya Café",
  "广告 / 活动名称": "Ad / Campaign name",
  "例如：雨天饮品优惠": "For example: Rainy-day drink offer",
  "投放开始日期": "Campaign start date",
  "投放结束日期": "Campaign end date",
  "意向区域（至少一项）": "Preferred areas (choose at least one)",
  "广告内容 / 其他要求": "Ad content / Other requests",
  "保存申请草稿": "Save application draft",
  "当前浏览器不支持定位，将继续使用演示位置。": "Location is not supported in this browser. Using the demo location.",
  "正在获取位置…": "Getting your location…",
  "已按 GPS 位置计算与演示伞点的距离。": "Distances to demo stations have been estimated from your GPS location.",
  "无法获取定位，继续使用世田谷演示位置。": "Location could not be obtained. Using the Setagaya demo location.",
  "已撤销损坏申报。": "Damage report withdrawn.",
  "已退出演示资料，借用记录仍保留在当前浏览器。": "Signed out. Loan records are still saved in this browser.",
  "已领取优惠券（演示）。": "Coupon saved (demo).",
  "已模拟使用优惠券。": "Coupon used in the demo.",
  "重置演示数据？": "Reset demo data?",
  "将清除当前浏览器内的资料、借用、记录、评价、收藏、优惠券和广告草稿，并重置库存。": "This clears the profile, loans, history, ratings, favorites, coupons and advertising drafts in this browser, and resets station stock.",
  "确认重置": "Confirm reset",
  "取消": "Cancel",
  "演示数据已重置。": "Demo data has been reset.",
  "已记录损坏（演示），尚未完成归还。": "Damage report saved (demo). The return is not yet complete.",
  "已登录演示资料。": "Signed in to demo profile.",
  "请输入昵称。": "Please enter a display name.",
  "资料已保存。": "Profile saved.",
  "编码不匹配，请输入界面上显示的演示码。": "The code does not match. Enter the demo code shown on screen.",
  "感谢反馈，评价已保存。": "Thank you. Your feedback has been saved.",
  "请输入企业名称及广告名称。": "Please enter a company name and campaign name.",
  "结束日期不能早于开始日期。": "The end date cannot be earlier than the start date.",
  "请至少选择一个投放区域。": "Please select at least one area.",
  "申请草稿已保存，未向外部发送。": "Draft saved locally. Nothing was sent externally."
};
